In [2]:
import math

In [3]:
import matplotlib.pyplot as plt

In [4]:
import numpy as np

In [5]:
from sklearn import datasets

In [6]:
iris = datasets.load_iris()

In [8]:
type(iris)

sklearn.utils.Bunch

In [9]:
from sklearn.naive_bayes import GaussianNB

In [13]:
type(iris.data)

numpy.ndarray

In [14]:
type(iris.target)

numpy.ndarray

In [21]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
iris.target[6]

0

In [23]:
gnb = GaussianNB()

In [24]:
gnb.fit(iris.data, iris.target)

GaussianNB(priors=None)

In [29]:
type(gnb)

sklearn.naive_bayes.GaussianNB

In [34]:
print(gnb.classes_)
print(gnb.class_count_)
print(gnb.class_prior_)
print(gnb.sigma_)

[0 1 2]
[50. 50. 50.]
[0.33333333 0.33333333 0.33333333]
[[0.121764 0.142276 0.029504 0.011264]
 [0.261104 0.0965   0.2164   0.038324]
 [0.396256 0.101924 0.298496 0.073924]]


In [40]:
y_pred = gnb.predict(iris.data)
print("Number of mislabeled points out of a total %d points : %d" % (iris.data.shape[0],(iris.target != y_pred).sum()))

Number of mislabeled points out of a total 150 points : 6


In [44]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris.data,iris.target, test_size=0.4, random_state=4)

# lets gather all the examples from class 0
def get_examples_for_class(class_id):
    examples = []
    for i, example in enumerate(X_train):
        if Y_train[i]==class_id:
            examples.append(example)
        
    examples = np.matrix(examples)
    return examples

examples = get_examples_for_class(0)
examples.shape

(25, 4)

In [55]:
mean = np.array(examples.mean(0))[0]
cov = np.cov(examples.T) # I don't know why you have to transpose the input to numpy... 
print(mean)
print(cov)

[4.964 3.416 1.44  0.24 ]
[[0.1049     0.06976667 0.01483333 0.00566667]
 [0.06976667 0.10723333 0.00391667 0.00266667]
 [0.01483333 0.00391667 0.02583333 0.00625   ]
 [0.00566667 0.00266667 0.00625    0.01      ]]


In [50]:
np.savetxt("/users/namudurr/downloads/data.csv", iris.data, delimiter=",")

In [51]:
np.savetxt("/users/namudurr/downloads/target.csv", iris.target, delimiter=",")

In [54]:
np.savetxt("/users/namudurr/downloads/examples.csv", examples, delimiter=",")

In [56]:
from scipy.stats import multivariate_normal

In [57]:
var = multivariate_normal(mean=mean, cov=cov)

In [58]:
var

In [63]:
X1=X_test[15]
import random
X1 = random.choice (X_test)
print(X1)

[5.7 4.4 1.5 0.4]


In [67]:
var.pdf(X1)

0.0867820712179773